# Generated by Django 3.0.5 on 2020-12-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('telephone_number', models.CharField(max_length=20, null=True)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('business_description', models.CharField(max_length=200, null=True)),
                ('logo', models.FileField(null=True, upload_to='')),
                ('website', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
